export const PROTETYK_COLUMNS = [
  "stan",
  "Spółka",
  "Data dodania CV",
  "Miasto",
  "Imię i Nazwisko",
  "Telefon",
  "Mail",
  "CV",
  "STATUS",
  "ETAP",
  "POWÓD ",
  "Notatka po ",
  "Nadaje    /    Nie nadaje się",
  "Aktualny etap procesu",
  "Data ostatniego kontaktu",
  "Kto prowadził rozmowę",
  "Notatka",
  "Lojalka",
  "Doświadczenie 1-5",
  "NFZ (tak/ nie/ w trakcie)",
  "Komunikatywność 1-5",
  "cv link",
  "ETAP II      Doświadczenie zawodowe",
  "ETAP II    Stabilnosc zatrudnienia",
  "ETAP II         Wiek",
  "Tytuł ogłoszenia",
  "ŹRÓDŁO CV",
  "Data publikacji",
  "Kto sprawdza"
] as const;

export const DORADCA_COLUMNS = [
  "f",
  "Stanowisko",
  "MIEJSCOWOŚĆ",
  "IMIĘ NAZWISKO",
  "NUMER TELEFONU ",
  "MAIL",
  "CV",
  "Notatka po CV",
  "Status (gdzie jest kandydat)",
  "szczegóły statusu",
  "Kto prowadził rozmowę",
  "notatka po rozmowie tel.",
  "spełnia wymagania systemowe?",
  "Zaprosić na szkolenie",
  "wysłana klauzula +warunki",
  "podpisane warunki + klauzula",
  "link do spotkania- wysłano sms?",
  "potwierdził przybycie?",
  "obecna 1 dzień?",
  "Obecna 2 dzień",
  "ocena z egzaminu",
  "Notatka ze szkolenia",
  "Zatrudnienie?",
  "ŹRÓDŁO",
  "Spółka"
] as const;

export const REQUIRED_CSV_COLUMNS = [...PROTETYK_COLUMNS, ...DORADCA_COLUMNS] as const;
